// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
contract = await Verifier.new()
// Test verification with correct proof
// - use the contents from proof.json generated from zokrates steps
proof = JSON.parse(fs.readFileSync("path/to/your/proof.json"))
await contract.verifyTx(proof.proof.a, proof.proof.b, proof.proof.c, proof.inputs)

// Test verification with incorrect proof
cheat = [...proof.inputs]
cheat[cheat.length-1] = cheat[cheat.length-1].replace(/[01]$/, cheat[cheat.length-1][65] == '1' ? '0': '1')

await contract.verifyTx(proof.proof.a, proof.proof.b, proof.proof.c, cheat)
